# Generated by Django 5.2.17 on 2026-09-24 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_graphic_design_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='owner_name',
            field=models.CharField(default='Hitul Nakrani', max_length=120),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='city',
            field=models.CharField(default='Visnagar, Mehsana, Gujarat, India', max_length=120),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='email',
            field=models.EmailField(default='Design.Hitul@gmail.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='phone',
            field=models.CharField(default='+91 70162 28333', max_length=40),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='tagline',
            field=models.CharField(default='We combine creativity, strategy and design to create stunning visuals that inspire and engage.', max_length=255),
        ),
    ]
