# Generated by Django 5.2.17 on 2026-09-25 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_contact_submission_html_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactsubmission',
            options={},
        ),
        migrations.AlterField(
            model_name='contactsubmission',
            name='phone',
            field=models.CharField(max_length=40),
        ),
    ]
