# Generated by Django 5.2.17 on 2026-09-25 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_align_contact_submission_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='read_time',
            field=models.PositiveSmallIntegerField(default=6),
        ),
        migrations.AddField(
            model_name='portfolioproject',
            name='challenge',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='portfolioproject',
            name='gallery_images',
            field=models.TextField(blank=True, help_text='One static image path per line'),
        ),
        migrations.AddField(
            model_name='portfolioproject',
            name='provided_services',
            field=models.TextField(blank=True, help_text='One service per line'),
        ),
        migrations.AddField(
            model_name='portfolioproject',
            name='result',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='portfolioproject',
            name='solution',
            field=models.TextField(blank=True),
        ),
    ]
