# Generated by Django 5.2.17 on 2026-09-25 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_preview_content_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=240)),
                ('answer', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'FAQ item',
                'verbose_name_plural': 'FAQ items',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-subscribed_at'],
            },
        ),
        migrations.CreateModel(
            name='PageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(max_length=40)),
                ('key', models.SlugField(max_length=100, unique=True)),
                ('value', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='page-content/')),
                ('active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Page content',
                'verbose_name_plural': 'Page content',
                'ordering': ['page', 'key'],
            },
        ),
        migrations.CreateModel(
            name='PageContentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(max_length=40)),
                ('section', models.CharField(max_length=60)),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('icon_class', models.CharField(blank=True, max_length=80)),
                ('image', models.ImageField(blank=True, upload_to='page-content/items/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['page', 'section', 'order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='service',
            name='detail_heading',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='service',
            name='detail_intro',
            field=models.TextField(blank=True, help_text='One paragraph per line'),
        ),
        migrations.AddField(
            model_name='service',
            name='feature_descriptions',
            field=models.TextField(blank=True, help_text='One description per feature line'),
        ),
        migrations.AddField(
            model_name='service',
            name='process_descriptions',
            field=models.TextField(blank=True, help_text='One description per process line'),
        ),
    ]
