# Generated by Django 5.2.17 on 2026-09-25 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_dynamic_page_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faqitem',
            options={'ordering': ['page', 'order', 'id'], 'verbose_name': 'FAQ item', 'verbose_name_plural': 'FAQ items'},
        ),
        migrations.AddField(
            model_name='faqitem',
            name='page',
            field=models.CharField(default='contact', max_length=40),
        ),
        migrations.AddField(
            model_name='pagecontentitem',
            name='button_text',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='pagecontentitem',
            name='button_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='pagecontentitem',
            name='eyebrow',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='pagecontentitem',
            name='value',
            field=models.CharField(blank=True, max_length=180),
        ),
    ]
