# Generated by Django 5.2.17 on 2026-09-27 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0016_add_page_content_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="gallery_image_descriptions",
            field=models.TextField(
                blank=True, help_text="One image description per gallery image line"
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="gallery_images",
            field=models.TextField(
                blank=True, help_text="One static image path per line"
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="gallery_videos",
            field=models.TextField(
                blank=True, help_text="One static video path per line"
            ),
        ),
    ]
